---
RSpec/UnusedLet:
  Description: Checks for `let` definitions that are never referenced.
  Enabled: true
  SafeAutoCorrect: false
  CheckLetBang: true
  CheckHelperSpecs: false
  Include:
    - "**/*_spec.rb"
    - "**/spec/**/*"
  VersionAdded: '1.0.0'
  VersionChanged: '1.2.0'
