---
RSpec/UnusedLet:
  Description: Checks for `let`/`subject` definitions and helper methods that are never referenced.
  Enabled: true
  SafeAutoCorrect: false
  CheckLetBang: true
  CheckSubject: true
  CheckHelperSpecs: false
  CheckSharedExamples: true
  SharedExamplePaths:
    - "spec/support/**/*.rb"
  Include:
    - "**/*_spec.rb"
    - "**/spec/**/*"
  VersionAdded: '1.0.0'
  VersionChanged: '1.2.0'
